name: Next Lint

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./end-user

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ env.working-directory }}/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Run Next Lint
        run: npm run lint
        working-directory: ${{ env.working-directory }}
